---

- hosts: all
  become: true
  pre_tasks:

  - name: install update CentOS
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution  == "CentOS"

  - name: install update Ubuntu
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: add-user
    user:
      name: simone
      groups:
        - root
      shell: /bin/bash
      createhome: yes
      home: /home/simone

  - name: add ssh-key for simone user
    tags: add-user
    authorized_key:
      user: simone
      key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

  - name: add sudoer file for simone user
    tags: add-user
    copy:
      src: simone
      dest: /etc/sudoers.d
      owner: root
      group: root
      mode: 0400

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php packages on Ubuntu
    tags: [ apache, ubuntu, apache2 ]
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution  == "Ubuntu"

  - name: install apache2 and php packages on CentOS
    tags: [ apache, centos, httpd ]
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution  == "CentOS"

  - name: start httpd service CentOS
    tags: [ apache, centos, httpd ]
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change admin email in default httpd config CentOS
    tags: [ apache, centos, httpd ]
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin admin@ansible-course.com
    when: ansible_distribution == "CentOS"
    register: httpd
# ??? check multiple tasks with the same register 
  - name: restart httpd service CentOS
    tags: [ apache, centos, httpd ]
    service:
      name: httpd
      state: restarted
    when: httpd.changed


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package CentOS
    tags: [ db, centos ]
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package Ubuntu
    tags: [ db, ubuntu ]
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
